name: libportal
buildsystem: meson
builddir: true
config-opts:
  - "-Dbackends=gtk3"
  - "-Ddocs=false"
sources:
  - type: archive
    url: https://github.com/flatpak/libportal/releases/download/0.5/libportal-0.5.tar.xz
    sha256: d8c8cb18a34e5eeb26a39c94044c955995b01de0e139caac5e18c076cf821b3b
